<?php

/**
 * @file
 * islandora_prepare_ingest.module
 *
 *
 *  Copyright 2017-2018 Leiden University Library
 *
 *  This file is part of islandora_prepare_ingest.
 *
 *  islandora_prepare_ingest is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Permissions.
define('ISLANDORA_PREPARE_INGEST_PREPARE', 'Prepare data for ingest into Islandora');
define('ISLANDORA_PREPARE_INGEST_MANAGE', 'Manage the workflows to prepare data for ingest into Islandora');

/**
 * Implements hook_menu().
 */
function islandora_prepare_ingest_menu() {
  $menu = array(
    'admin/islandora/prepare_ingest' => array(
      'title' => 'Prepare Ingest',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_manage_form'),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/make' => array(
      'title' => 'Make generic workflow',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_edit_workflow_form'),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/edit/%' => array(
      'title' => 'Edit generic workflow',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_edit_workflow_form', 4, 'edit'),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/copy/%' => array(
      'title' => 'Copy generic workflow',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_copy_workflow_form',4),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/export/%' => array(
      'title' => 'Export generic workflow',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_export_workflow_form',4),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/dryrun/%' => array(
      'title' => 'Check generic workflow',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_prepare_ingest_edit_workflow_form', 4, 'dryrun'),
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/prepare_ingest/ajax/addstep/%/%' => array(
      'page callback' => 'islandora_prepare_ingest_ajax_addstep_handler',
      'page arguments' => array(5,6),
      'delivery callback' => 'islandora_prepare_ingest_ajax_delivery_handler',
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_CALLBACK,
    ),
    'admin/islandora/prepare_ingest/ajax/addstepsgroup/%/%' => array(
      'page callback' => 'islandora_prepare_ingest_ajax_addstepsgroup_handler',
      'page arguments' => array(5,6),
      'delivery callback' => 'islandora_prepare_ingest_ajax_delivery_handler',
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_CALLBACK,
    ),
    'admin/islandora/prepare_ingest/ajax/datacache' => array(
      'page callback' => 'islandora_prepare_ingest_ajax_datacache_handler',
      'page arguments' => array(),
      'delivery callback' => 'islandora_prepare_ingest_ajax_delivery_handler',
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_CALLBACK,
    ),
    'admin/islandora/prepare_ingest/ajax/files' => array(
      'page callback' => 'islandora_prepare_ingest_ajax_files_handler',
      'page arguments' => array(),
      'delivery callback' => 'islandora_prepare_ingest_ajax_delivery_handler',
      'file' => 'includes/manage.form.inc',
      'access arguments' => array(ISLANDORA_PREPARE_INGEST_MANAGE),
      'type' => MENU_CALLBACK,
    ),
  );
  return $menu;
}

/**
 * Implements hook_permission().
 */
function islandora_prepare_ingest_permission() {
  return array(
    ISLANDORA_PREPARE_INGEST_PREPARE => array(
      'title' => t('Prepare ingest'),
      'description' => t('Prepare data for ingest into Islandora'),
    ),
    ISLANDORA_PREPARE_INGEST_MANAGE => array(
      'title' => t('Manage workflows'),
      'description' => t('Manage the workflows to prepare data for ingest into Islandora'),
    ),
  );
}

/**
 * Implements hook_hook_info().
 */
function islandora_prepare_ingest_hook_info() {
  $hooks['workflow_step_info'] = array(
    'group' => 'workflow_step',
  );
  return $hooks;
}
