<?php

/**
 * @file
 * ubl_show_persistent_url module.
 */

/**
 * Alter display output after it has been generated.
 *
 * @param AbstractObject $object
 *   A Tuque AbstractObject being operated on.
 * @param array $rendered
 *   The array of rendered views.
 */
function ubl_show_persistent_url_islandora_view_object_alter(&$object, &$rendered) {
  if ($object) {
    $title = drupal_get_title();
    $label = t('persistent url');
    $class = "ublpersistentbutton";
    if ((strpos($title, $label) !== FALSE) && (strpos($title, $class) !== FALSE)) {
      return;
    }
    $url = '';
    if (module_exists("islandora_handle")) {
      if (isset($object['MODS'])) {
        $xpath = "/mods:mods/mods:identifier[@type='hdl']";
        $content = $object['MODS']->content;
        $domdoc = new DOMDocument();
        if ($domdoc->loadXML($content)) {
          $domxpath = new DOMXPath($domdoc);
          $domxpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
          $domnodelist = $domxpath->query($xpath);
          if ($domnodelist->length > 0) {
            foreach ($domnodelist as $domnode) {
              $text = $domnode->textContent;
              if (isset($text) && strlen($text) > 0) {
                $url = $text;
                break;
              }
            }
          }
        }
      }
    }
    if (strlen($url) == 0) {
      $url = url("islandora/object/" . $object->id, array('absolute' => TRUE));
    }
    $title .= " <A href=\"$url\" class=\"$class\" data-title=\"$label\"></A>";
    drupal_set_title($title, PASS_THROUGH);
  }
}
